import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import NavigationCard from '../components/Navigation/card'
import CardWithGlow from '../components/Navigation/glowButton'
import ContentNavigation from '../components/Navigation'
import LiteratureContent from '../components/Carusel/Literature'

export default function Home() {
  return (
    <div className={styles.window}>
      <Head>
        <title>Klassenspiel 2022</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ContentNavigation />

      <LiteratureContent />
    </div>
  )
}
