import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import NavigationCard from '../components/Navigation/card'

export default function Home() {
  return (
    <div className={styles.window}>
      <Head>
        <title>Aliyas tolle website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavigationCard 
        backgroundColor={"#B197CF"}
        buttonBackgroundColor={"#9A7BBD"}
        buttonBorderColor={'#542784'}
        buttonColor={"#fff"}
        textColor={"#fff"}
      />
    </div>
  )
}
